const login=document.querySelector('#login'),dash=document.querySelector('#dashboard'),loginForm=document.querySelector('#loginForm'),msg=document.querySelector('#loginMsg'),dashboardMsg=document.querySelector('#dashboardMsg'),rows=document.querySelector('#rows'),stats=document.querySelector('#stats'),logout=document.querySelector('#logout');
let csrfToken='';
let offset=0;
const pageSize=50;
const analytics=document.querySelector('#analytics');
const loadMore=document.querySelector('#loadMore');
const sourceForm=document.querySelector('#sourceForm'), sourceMsg=document.querySelector('#sourceMsg'), sourceList=document.querySelector('#sources');
async function jsonOrError(response){const type=response.headers.get('content-type')||'';const data=type.includes('application/json')?await response.json():{};if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
async function establishSession(){const r=await fetch('/api/admin/session',{cache:'no-store'});if(!r.ok)return false;const d=await jsonOrError(r);csrfToken=d.csrfToken||'';return Boolean(csrfToken);}
function renderRows(leads){rows.insertAdjacentHTML('beforeend',leads.map(x=>`<tr><td>#${esc(x.id)}</td><td><b>${esc(x.name)}</b><br><small>${esc(x.phone)} · ${esc(x.email)}</small></td><td>${esc(x.service)}</td><td>$${Number(x.estimate_min).toLocaleString()}–$${Number(x.estimate_max).toLocaleString()}</td><td><span class="pill ${esc(x.ai_priority)}">${esc(x.ai_priority)}</span></td><td><b>${esc(x.lead_score)}</b>/100</td><td>${esc(x.next_action)}</td><td>${esc(x.source||'website')}</td><td>${esc(x.industry||'general')}</td><td><select data-id="${esc(x.id)}" class="status"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='contacted'?'selected':''}>contacted</option><option ${x.status==='booked'?'selected':''}>booked</option><option ${x.status==='completed'?'selected':''}>completed</option><option ${x.status==='lost'?'selected':''}>lost</option></select></td><td>${esc(new Date(x.created_at).toLocaleString())}</td></tr>`).join(''));bindStatuses();}
function bindStatuses(){document.querySelectorAll('.status:not([data-bound])').forEach(s=>{s.dataset.bound='1';s.addEventListener('change',async()=>{s.disabled=true;try{const r=await fetch('/api/admin/leads/'+encodeURIComponent(s.dataset.id),{method:'PATCH',headers:{'content-type':'application/json','x-csrf-token':csrfToken},body:JSON.stringify({status:s.value})});await jsonOrError(r);}catch(err){const error=err.message||'Could not update lead.';await load(true);if(dashboardMsg) dashboardMsg.textContent=error;}finally{s.disabled=false;}});});}
async function load(reset=false){try{if(dashboardMsg) dashboardMsg.textContent='';if(reset){offset=0;rows.textContent='';}if(!csrfToken && !(await establishSession())){login.hidden=false;dash.hidden=true;logout.hidden=true;return;}const r=await fetch(`/api/admin/leads?limit=${pageSize}&offset=${offset}`,{cache:'no-store'});if(r.status===401){csrfToken='';login.hidden=false;dash.hidden=true;logout.hidden=true;return;}const d=await jsonOrError(r);login.hidden=true;dash.hidden=false;logout.hidden=false;stats.innerHTML=`<div class="stat"><span>Leads</span><b>${Number(d.stats.total).toLocaleString()}</b></div><div class="stat"><span>Potential value</span><b>$${Number(d.stats.value).toLocaleString()}</b></div><div class="stat"><span>New</span><b>${Number(d.stats.new).toLocaleString()}</b></div><div class="stat"><span>Hot</span><b>${Number(d.stats.hot).toLocaleString()}</b></div><div class="stat"><span>Booked</span><b>${Number(d.stats.booked).toLocaleString()}</b></div>`; await loadAnalytics();renderRows(d.leads);offset+=d.leads.length;loadMore.hidden=!d.pagination.hasMore;}catch(err){if(dashboardMsg) dashboardMsg.textContent=err.message||'Could not load the dashboard. Refresh and try again.';}}
loginForm.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='';try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:document.querySelector('#password').value})});const d=await jsonOrError(r);document.querySelector('#password').value='';csrfToken=d.csrfToken||'';if(d.ok)await load(true);}catch(err){msg.textContent=err.message||'Login failed.';}});
logout.addEventListener('click',async()=>{try{if(csrfToken)await fetch('/api/admin/logout',{method:'POST',headers:{'x-csrf-token':csrfToken}});}finally{csrfToken='';await load(true);}});
loadMore?.addEventListener('click',()=>load(false));
function esc(v){const m={'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'};return String(v??'').replace(/[&<>'"]/g,c=>m[c]||c);}
load();

async function loadSources(){ if(!sourceList) return; try{ const r=await fetch('/api/admin/sources',{cache:'no-store'}); const d=await jsonOrError(r); sourceList.innerHTML=d.sources.map(x=>`<div class="source-row"><div><b>${esc(x.name)}</b><br><small>${esc(x.kind)} · ${esc(x.industry)} · ${x.enabled?'enabled':'disabled'}${x.last_error?' · last sync error':''}</small></div><button class="ghost sync-source" data-id="${esc(x.id)}" ${x.enabled?'':'disabled'}>Sync</button></div>`).join(''); document.querySelectorAll('.sync-source').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{const r=await fetch('/api/admin/sources/'+encodeURIComponent(b.dataset.id)+'/sync',{method:'POST',headers:{'x-csrf-token':csrfToken}});await jsonOrError(r);await load(true);await loadSources();}catch(e){sourceMsg.textContent=e.message||'Sync failed.';}finally{b.disabled=false;}})); }catch(e){sourceMsg.textContent=e.message||'Could not load sources.';} }
sourceForm?.addEventListener('submit',async e=>{e.preventDefault();sourceMsg.textContent='';try{const r=await fetch('/api/admin/sources',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrfToken},body:JSON.stringify({name:document.querySelector('#sourceName').value,kind:document.querySelector('#sourceKind').value,industry:document.querySelector('#sourceIndustry').value,externalId:document.querySelector('#sourceExternalId').value,endpoint:document.querySelector('#sourceEndpoint').value,accessToken:document.querySelector('#sourceToken').value})});await jsonOrError(r);sourceForm.reset();await loadSources();}catch(e){sourceMsg.textContent=e.message||'Could not add source.';}});
const originalLoad=load; load=async function(reset=false){await originalLoad(reset); if(csrfToken) await loadSources();};

async function loadAnalytics(){ if(!analytics)return; try{const r=await fetch('/api/admin/analytics',{cache:'no-store'});const d=await jsonOrError(r);analytics.hidden=false;analytics.innerHTML='<div class="eyebrow">LEAD INTELLIGENCE</div><h2>Where the opportunities are</h2><p><b>'+Number(d.overdueFollowups).toLocaleString()+'</b> follow-ups are due.</p><div class="analytics-grid"><div><b>By source</b>'+d.bySource.map(x=>'<div>'+esc(x.source)+' · '+Number(x.count).toLocaleString()+' leads · $'+Number(x.value).toLocaleString()+'</div>').join('')+'</div><div><b>By industry</b>'+d.byIndustry.slice(0,8).map(x=>'<div>'+esc(x.industry)+' · '+Number(x.count).toLocaleString()+' leads · $'+Number(x.value).toLocaleString()+'</div>').join('')+'</div></div>';}catch(e){analytics.textContent=e.message||'Analytics unavailable.';}}
