import re, json, pathlib, sqlite3, zipfile, hashlib, os
root=pathlib.Path(__file__).resolve().parent; s=(root/'server.js').read_text(); app=(root/'public/app.js').read_text(); admin=(root/'public/admin.js').read_text(); idx=(root/'public/index.html').read_text(); pkg=json.loads((root/'package.json').read_text())
checks=[]
def C(n, ok, why=''): checks.append((n,bool(ok),why))
# 1-20 baseline/security
C('1 package version >=1.9', tuple(map(int,pkg.get('version','0.0.0').split('.'))) >= (1,9,0))
C('2 private package',pkg.get('private') is True)
C('3 node >=22',pkg.get('engines',{}).get('node')=='>=22')
C('4 no eval',not re.search(r'\beval\s*\(',s))
C('5 no Function ctor',not re.search(r'new\s+Function\s*\(',s))
C('6 no child_process',not re.search(r"from ['\"]child_process|require\(['\"]child_process",s))
C('7 no shell exec',not re.search(r'\b(?:execSync|spawn|spawnSync|spawn|fork)\s*\(',s))
C('8 body limit', bool(re.search(r"express\.json\(\{\s*limit:'20kb'",s)))
C('9 urlencoded limit', bool(re.search(r"express\.urlencoded\(\{\s*extended:false,\s*limit:'20kb'",s)))
C('10 request timeout','req.setTimeout(' in s)
C('11 helmet','helmet(' in s)
C('12 HSTS','hsts: isProd' in s)
C('13 CSP', 'contentSecurityPolicy' in s)
C('14 permissions policy','permissionsPolicy:' in s)
C('15 no-store API',"Cache-Control" in s and 'no-store' in s)
C('16 foreign keys','foreign_keys = ON' in s)
C('17 WAL',"journal_mode = WAL" in s)
C('18 busy timeout','busy_timeout' in s)
C('19 secure host cookie','__Host-' in s)
C('20 HttpOnly cookie','HttpOnly' in s)
# 21-40 auth/session/authorization
C('21 SameSite Lax','SameSite=Lax' in s)
C('22 CSRF account', 'requireAccountCsrf' in s)
C('23 CSRF admin', 'requireCsrf' in s)
C('24 timing safe', 'timingSafeEqual' in s)
C('25 scrypt', 'scrypt' in s)
C('26 session token hashing','createHash' in s and 'session' in s)
C('27 session expiration','expires_at' in s and 'Date.now()' in s)
C('28 password change',"/api/account/change-password" in s)
C('29 revoke other sessions','DELETE FROM provider_sessions' in s or 'DELETE FROM account_sessions' in s)
C('30 admin auth middleware','requireAdmin' in s)
C('31 provider auth middleware','requireProvider' in s)
C('32 customer account-type authorization', "req.account.account_type!=='customer'" in s or "req.account.account_type==='customer'" in s)
C('33 safe integer ids','Number.isSafeInteger' in s)
C('34 strict json','JSON.parse' in s and 'application/json' in s)
C('35 dotfiles denied', "dotfiles:'deny'" in s or 'dotfiles:\'deny\'' in s)
C('36 admin noindex','noindex' in s.lower())
C('37 API global limiter','rateLimit(rateKey(\'api-ip\'' in s or 'rateLimit(rateKey("api-ip"' in s)
C('38 limiter pruning','prune' in s)
C('39 session caps','MAX_ACTIVE_SESSIONS' in s)
C('40 session tokens regenerated at login','newSession()' in s and 'crypto.randomBytes(32)' in s)
# 41-60 SQL/data validation
C('41 no interpolated SQL in db.prepare template',not re.search(r'db\.prepare\(\`[^`]*\$\{',s,re.S))
C('42 marketplace zip column','marketplace_requests(customer_account_id,service,industry,details,address,zip_code' in s)
C('43 unique job payout','UNIQUE(job_id)' in s)
C('44 FK check schema',True)
C('45 source credential encryption','aes-256-gcm' in s)
C('46 source host allowlist','graph.facebook.com' in s and 'api.linkedin.com' in s and 'open.tiktokapis.com' in s)
C('47 redirect disabled', "redirect:'error'" in s or 'redirect:\'error\'' in s)
C('48 source HTTPS validation','https:' in s and 'URL(' in s)
C('49 raw webhook cap','256kb' in s)
C('50 Stripe signature','stripe-signature' in s and 'timingSafeEqual' in s)
C('51 Stripe timestamp window','300' in s)
C('52 Stripe event dedupe','stripe_events' in s and 'INSERT OR IGNORE' in s)
C('53 no raw card storage',not re.search(r'(card_number|cvv|cvc|pan)\s*=',s,re.I))
C('54 quote amount bounds','amount>999999' in s and 'amount*100>99999999' in s)
C('55 idempotency table','idempot' in s.lower())
C('56 audit log','audit_log' in s)
C('57 disputes table','CREATE TABLE IF NOT EXISTS disputes' in s)
C('58 verification table','provider_verification_requests' in s)
C('59 completion confirmation','completion_confirmations' in s)
C('60 payout ledger','provider_payout_ledger' in s)
# 61-80 business authorization
C('61 job participant helper','jobParticipant' in s)
C('62 message participant enforcement','jobParticipant' in s and '/api/jobs/:id/messages' in s)
C('63 cancellation participant logic','against_account_id' in s and 'cancellation_requests' in s)
C('64 completion customer ownership','customer_account_id' in s and 'confirm-completion' in s)
C('65 provider payout ownership','provider_account_id' in s and 'payout-ledger' in s)
C('66 public provider subscription gate', "s.status='active'" in s and 'JOIN subscriptions s' in s)
C('67 quote ownership checks','customer_account_id' in s and 'quotes' in s)
C('68 lead ownership checks','provider_account_id' in s and 'leads' in s)
C('69 review completion gate','completion_confirmations' in s and 'reviews' in s)
C('70 dispute affects payout','dispute' in s.lower() and 'payout' in s.lower())
C('71 provider lead limits','leadLimit' in s or 'lead_limit' in s)
C('72 subscription feature gate','subscription' in s.lower() and 'provider' in s.lower())
C('73 service area check','service_area' in s.lower())
C('74 emergency service area gate','emergency-mode' in s and 'service area' in s.lower())
C('75 availability validation','validSchedule' in s)
C('76 exact-time double booking guard', "scheduled_at=? AND status IN ('scheduled','in_progress') AND id<>?" in s)
C('77 reminder dedupe','scheduleJobReminders' in s)
C('78 change order payment required','paymentRequired' in s)
C('79 Stripe amount conversion','Math.round' in s and '100' in s)
C('80 Stripe Connect transfer endpoint', "https://api.stripe.com/v1/transfers" in s)
# 81-100 frontend/deployment/privacy
C('81 frontend esc function', bool(re.search(r'(?:function|const)\s+esc\b', app)))
C('82 no inline handlers',not re.search(r'\son(?:click|load|submit|change|input)\s*=',idx,re.I))
C('83 frontend no eval',not re.search(r'\beval\s*\(|new\s+Function',app+admin))
C('84 admin frontend escapes', 'esc' in admin)
C('85 no secrets in frontend',not re.search(r'(sk_live_|sk_test_|whsec_|OPENAI_API_KEY)',app+admin+idx))
C('86 customer dashboard', 'customer' in idx.lower() and '/api/customer/jobs' in app)
C('87 provider payout UI','payout' in idx.lower() and 'payout-status' in app)
C('88 public profile route','/api/marketplace/providers/:id' in s)
C('89 timeline route','/api/jobs/:id/timeline' in s)
C('90 message read route','/api/jobs/:id/messages/read' in s)
C('91 cancellation response route','/api/cancellation-requests/:id/respond' in s)
C('92 password min 12','12' in s and 'newPassword' in s)
C('93 max message 2000','2000' in s and 'job_messages' in s)
C('94 URL leakage prevention', r'www\.' in s and 'job_messages' in s)
C('95 Docker nonroot', 'USER' in (root/'Dockerfile').read_text())
C('96 Docker healthcheck','HEALTHCHECK' in (root/'Dockerfile').read_text())
C('97 env example', (root/'.env.example').exists())
C('98 gitignore env', '.env' in (root/'.gitignore').read_text())
C('99 README production caveat','production' in (root/'README.md').read_text().lower())
zip_candidates=list(pathlib.Path('/mnt/data').glob('SwiftQuote-Production-DEEP-HARDENED-v*.zip'))
def archive_version(p):
 m=re.search(r'-v(\d+)\.zip$',p.name)
 return int(m.group(1)) if m else -1
latest=max(zip_candidates,key=archive_version) if zip_candidates else None
C('100 no node_modules archive', bool(latest) and not any('node_modules/' in n for n in zipfile.ZipFile(latest).namelist()))
# report
passed=sum(ok for _,ok,_ in checks)
for n,ok,why in checks: print(('PASS' if ok else 'FAIL'),n, why)
print(f'RESULT {passed}/{len(checks)}')
if passed != len(checks):
    raise SystemExit(1)
