#!/usr/bin/env python3
import json,re,sqlite3,zipfile,hashlib,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parent
SRC=(ROOT/'server.js').read_text()
APP=(ROOT/'public/app.js').read_text()
ADM=(ROOT/'public/admin.js').read_text()
PKG=json.loads((ROOT/'package.json').read_text())
results=[]
def check(name,cond,detail=''):
    results.append((name,bool(cond),detail))

def has(x): return x in SRC
# 1-20 package / syntax / artifact controls
check('package version >= 1.10', tuple(map(int,PKG['version'].split('.'))) >= (1,10,0))
check('private package', PKG.get('private') is True)
check('node >=22', PKG.get('engines',{}).get('node')=='>=22')
check('start script', PKG.get('scripts',{}).get('start')=='node server.js')
check('dev script', PKG.get('scripts',{}).get('dev')=='node --watch server.js')
check('ES module', PKG.get('type')=='module')
check('better-sqlite3 pinned', PKG['dependencies'].get('better-sqlite3')=='11.10.0')
check('express pinned', PKG['dependencies'].get('express')=='5.1.0')
check('helmet pinned', PKG['dependencies'].get('helmet')=='8.1.0')
check('dotenv pinned', PKG['dependencies'].get('dotenv')=='16.6.1')
check('openai pinned', PKG['dependencies'].get('openai')=='6.5.0')
check('default OpenAI model is documented gpt-4.1-mini', "OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-4.1-mini'" in SRC)
check('env example model matches server', 'OPENAI_MODEL=gpt-4.1-mini' in (ROOT/'.env.example').read_text())
check('Gemini fallback module imported', "import { createAIProvider } from './ai-provider.js'" in SRC)
check('Gemini API key configured server-side', "const GEMINI_API_KEY = process.env.GEMINI_API_KEY || ''" in SRC)
check('AI provider checks shared configuration', 'if(ai.configured)' in SRC and '!ai.configured' in SRC)
check('Gemini API key not shipped to frontend', 'GEMINI_API_KEY' not in APP + ADM)
check('AI provider tests included', (ROOT/'test/ai-provider.test.js').exists())
check('no eval', not re.search(r'\beval\s*\(',SRC))
check('no Function constructor', not re.search(r'\bnew\s+Function\s*\(',SRC))
check('no child_process', 'child_process' not in SRC)
check('no shell execution', not re.search(r'\b(?:execFile|spawn|fork)\s*\(',SRC) and 'child_process' not in SRC)
check('no secrets files', not any((ROOT/x).exists() for x in ['.env','.env.local','.env.production']))
check('no db artifact', not any(p.suffix in {'.db','.sqlite','.sqlite3'} for p in ROOT.rglob('*') if p.is_file()))
check('no private key artifact', not any(p.suffix in {'.pem','.key','.p12'} for p in ROOT.rglob('*') if p.is_file()))
check('env example present', (ROOT/'.env.example').exists())
check('gitignore present', (ROOT/'.gitignore').exists())
# 21-45 server hardening
check('x-powered-by disabled', has("app.disable('x-powered-by')"))
check('helmet enabled', has('app.use(helmet('))
check('CSP self scripts', "scriptSrc:[\"'self'\"]" in SRC)
check('CSP object none', 'objectSrc:' in SRC and "'none'" in SRC[SRC.find('objectSrc:'):SRC.find('objectSrc:')+80])
check('frame ancestors none', "frameAncestors:[\"'none'\"]" in SRC)
check('base uri self', 'baseUri:' in SRC and "'self'" in SRC[SRC.find('baseUri:'):SRC.find('baseUri:')+80])
check('form action self', 'formAction:' in SRC and "'self'" in SRC[SRC.find('formAction:'):SRC.find('formAction:')+80])
check('referrer policy', 'referrerPolicy:' in SRC)
check('permissions policy', 'permissionsPolicy:' in SRC)
check('HSTS production', 'hsts: isProd' in SRC and 'maxAge: 31536000' in SRC)
check('JSON body cap', 'express.json(' in SRC and "limit:'20kb'" in SRC[SRC.find('express.json('):SRC.find('express.json(')+100])
check('urlencoded body cap', 'express.urlencoded(' in SRC and "limit:'20kb'" in SRC[SRC.find('express.urlencoded('):SRC.find('express.urlencoded(')+120])
check('raw Stripe cap', "express.raw({type:'application/json',limit:'256kb'})" in SRC)
check('request timeout', 'server.requestTimeout = 15_000' in SRC)
check('headers timeout', 'server.headersTimeout = 10_000' in SRC)
check('keepalive timeout', 'server.keepAliveTimeout = 5_000' in SRC)
check('max headers count', 'server.maxHeadersCount = 100' in SRC)
check('API no-store helper', "res.set('Cache-Control','no-store')" in SRC)
check('dotfiles denied', 'dotfiles:' in SRC and "'deny'" in SRC[SRC.find('dotfiles:'):SRC.find('dotfiles:')+40])
check('admin noindex', 'X-Robots-Tag' in SRC and 'noindex' in SRC)
check('global API limiter', "app.use('/api'" in SRC and "rateKey('api-ip',clientIp(req))" in SRC)
check('limiter pruning', 'setInterval(pruneAttempts' in SRC)
check('trust proxy bounded', 'TRUST_PROXY_HOPS > 10' in SRC)
check('production HTTPS origin', "APP_ORIGIN must use HTTPS in production" in SRC)
# 46-75 auth / session
check('scrypt password hashing', 'crypto.scryptSync' in SRC)
check('timing safe password compare', 'crypto.timingSafeEqual' in SRC)
check('session HMAC hashing', 'createHmac' in SRC and 'tokenHash' in SRC)
check('random session token', 'randomBytes(32)' in SRC)
check('random csrf token', 'const csrf=crypto.randomBytes(32)' in SRC)
check('admin session expiry', 'expires_at' in SRC and 'SESSION_TTL_MS' in SRC)
check('provider session expiry', 'PROVIDER_SESSION_TTL_MS' in SRC)
check('secure production cookie', "if(isProd)parts.push('Secure')" in SRC)
check('HttpOnly account cookie', "'HttpOnly'" in SRC)
check('SameSite Lax', "'SameSite=Lax'" in SRC)
check('host prefix production', "'__Host-sq_account'" in SRC and "'__Host-sq_session'" in SRC)
check('account CSRF middleware', 'function requireAccountCsrf' in SRC)
check('admin CSRF middleware', 'function requireCsrf' in SRC)
check('same-origin enforcement', 'function sameOrigin' in SRC)
check('login rate limit IP', "rateKey('login',clientIp(req))" in SRC)
check('login rate limit email', "rateKey('login-email',email)" in SRC)
check('registration rate limit', "rateKey('register',clientIp(req))" in SRC)
check('password minimum 12', 'password.length<12' in SRC)
check('password maximum 200', 'password.length>200' in SRC)
check('password session revocation', 'DELETE FROM provider_sessions WHERE account_id=? AND token_hash<>?' in SRC)
check('active session cap', 'MAX_ACTIVE_SESSIONS' in SRC and 'slice(MAX_ACTIVE_SESSIONS)' in SRC)
check('provider session cap', 'active.slice(5)' in SRC)
check('production secret gate', 'Refusing production startup: SESSION_SECRET' in SRC)
check('production admin password gate', 'Refusing production startup: ADMIN_PASSWORD' in SRC)
check('CSRF timing-safe compare', 'timingSafeEqual(Buffer.from(supplied)' in SRC)
check('cookie raw token format', "^[A-Za-z0-9_-]{43}$" in SRC)
# 76-105 authorization / route inventory
routes=re.findall(r"app\.(get|post|put|patch|delete)\(['\"]([^'\"]+)",SRC)
keys=[f'{m.upper()} {p}' for m,p in routes]
check('route inventory extracted', len(routes)>=80,str(len(routes)))
check('no duplicate routes', len(keys)==len(set(keys)),f'{len(keys)} routes')
def route_chunk(method,path):
    marker=f"app.{method.lower()}('{path}'"
    i=SRC.find(marker)
    return SRC[i:i+700] if i>=0 else ''
check('admin mutators protected', all(('requireAdmin' in route_chunk(m,p) and 'requireCsrf' in route_chunk(m,p)) for m,p in routes if p.startswith('/api/admin/') and m in {'post','put','patch','delete'} and p!='/api/admin/login'))
check('account mutators mostly CSRF', all('requireAccountCsrf' in route_chunk(m,p) for m,p in routes if p.startswith('/api/account/') and m in {'post','put','patch','delete'} and p not in {'/api/account/register','/api/account/login'}))
check('provider mutators CSRF', all('requireAccountCsrf' in route_chunk(m,p) for m,p in routes if p.startswith('/api/provider/') and m in {'post','put','patch','delete'}))
check('job mutators auth', all('requireAccount' in route_chunk(m,p) for m,p in routes if p.startswith('/api/jobs/') and m in {'post','put','patch','delete'}))
check('admin login same-origin', "if(!sameOrigin(req)) return res.status(403)" in SRC)
check('account register same-origin', "if(!sameOrigin(req))return res.status(403)" in SRC)
check('account login same-origin', "if(!sameOrigin(req))return res.status(403)" in SRC)
check('marketplace request same-origin', "app.post('/api/marketplace/request'" in SRC and "sameOrigin(req)" in SRC[SRC.find("app.post('/api/marketplace/request'"):SRC.find("app.post('/api/marketplace/request'")+1000])
check('source intake secret compare', 'timingSafeEqual(Buffer.from(supplied)' in SRC)
check('source IDs safe integer', 'Number.isSafeInteger(id)' in SRC)
check('job participant helper', 'function jobParticipant' in SRC)
check('message participant enforcement', 'jobParticipant(id,req.account.account_id)' in SRC)
check('cancellation participant enforcement', 'jobParticipant(id,req.account.account_id)' in SRC)
check('customer job ownership', 'l.customer_account_id=?' in SRC)
check('provider job ownership', 'provider_account_id=?' in SRC)
check('provider quote requires claimed lead', "match.status!=='claimed'" in SRC)
check('subscription gate receive', 'providerCanReceive' in SRC)
check('lead claim limit', 'providerCanClaim' in SRC)
check('payout ownership', 'l.provider_account_id=?' in SRC)
check('notification ownership', 'account_id=?' in SRC)
check('review customer ownership', 'l.customer_account_id=?' in SRC)
# 106-135 SQL/data integrity
sql=re.findall(r"db\.exec\(`([\s\S]*?)`\);",SRC)
check('schema block found', bool(sql))
schema=sql[0] if sql else ''
con=sqlite3.connect(':memory:')
try:
    con.execute('PRAGMA foreign_keys=ON')
    con.executescript(schema)
    fk=con.execute('PRAGMA foreign_key_check').fetchall()
    check('schema executes',True)
    check('schema FK clean',not fk,str(fk[:3]))
    tables={r[0] for r in con.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    for t in ['accounts','leads','quotes','jobs','reviews','subscriptions','payment_holds','provider_payout_ledger','job_agreements','change_orders','job_messages','job_status_events','cancellation_requests','completion_confirmations','disputes','provider_verification_requests','provider_availability','risk_events','audit_log']:
        check(f'table {t}',t in tables)
    check('reviews unique lead', 'lead_id INTEGER NOT NULL UNIQUE' in schema[schema.find('CREATE TABLE IF NOT EXISTS reviews'):schema.find('CREATE TABLE IF NOT EXISTS account_notifications')])
    check('jobs unique lead', 'lead_id INTEGER NOT NULL UNIQUE' in schema[schema.find('CREATE TABLE IF NOT EXISTS jobs'):schema.find('CREATE TABLE IF NOT EXISTS reviews')])
    check('payout unique job', 'UNIQUE(job_id)' in schema[schema.find('CREATE TABLE IF NOT EXISTS provider_payout_ledger'):])
    check('idempotency composite PK', 'PRIMARY KEY(account_id, scope, idem_key)' in schema)
    check('accounts unique email', 'email TEXT NOT NULL UNIQUE' in schema)
finally: con.close()
check('parameter placeholders prevalent', len(re.findall(r'db\.prepare\([^\n]*\?[^\n]*\)',SRC))>40)
check('no obvious SQL string interpolation from req body', not re.search(r'prepare\(`[^`]*\$\{req\.(body|query|params)',SRC))
check('audit helper parameterized', "INSERT INTO audit_log(account_id" in SRC)
check('risk metadata JSON', 'JSON.stringify(metadata)' in SRC)
check('PII not returned from trust card', 'password_hash' not in SRC[SRC.find("/api/provider/trust-card"):SRC.find("/api/provider/trust-card")+1200])
check('public provider excludes zip_codes raw', "const {zip_codes,services_json,...safe}=p" in SRC)
# 136-165 payment / Stripe
check('Stripe signature HMAC', 'STRIPE_WEBHOOK_SECRET' in SRC and 'hmacHex' in SRC)
check('Stripe timestamp window', '300' in SRC[SRC.find("/api/billing/stripe-webhook"):SRC.find("/api/billing/stripe-webhook")+1500])
check('Stripe raw body verification', 'Buffer.from(req.body).toString' in SRC)
check('Stripe event dedupe', 'INSERT OR IGNORE INTO stripe_events' in SRC)
check('quote amount cents conversion', 'q.amount*100' in SRC)
check('change amount cents conversion', 'co.amount_delta*100' in SRC)
check('payout cents conversion', 'Number(row.amount)*100' in SRC)
check('refund cents conversion', 'Math.abs(co.amount_delta)*100' in SRC)
check('quote max amount', 'amount>999999' in SRC)
check('change order max amount', 'Math.abs(delta)>999999' in SRC)
check('Stripe session exact quote match', 'clean(o.id,255)===clean(hold.external_id,255)' in SRC)
check('Stripe session exact change match', 'changeSessionMatches' in SRC)
check('Stripe customer match quote', 'customerId!==Number(q.customer_account_id)' in SRC)
check('Stripe customer match change', 'customerId!==Number(co.customer_account_id)' in SRC)
check('Stripe currency match quote', 'currencyOk' in SRC)
check('change refund cap', 'requestedRefund+priorRefunded>originalPaid' in SRC)
check('payout dispute freeze', "status IN ('open','investigating')" in SRC)
check('payout completion confirmation', 'completion_confirmations' in SRC)
check('payout Connect destination', 'destination' in SRC[SRC.find("app.post('/api/provider/payouts/"):SRC.find("app.post('/api/provider/payouts/")+2500])
check('payout idempotency', 'swiftquote-payout-' in SRC)
check('Connect account idempotency', 'swiftquote-connect-account-' in SRC)
check('subscription plan price map', 'STRIPE_PROVIDER_PRICE_IDS' in SRC)
check('production requires all Stripe plan IDs', 'missingStripePlans' in SRC)
check('no raw card storage', 'card_number' not in SRC.lower() and 'cvc' not in SRC.lower())
check('payment hold ledger', 'CREATE TABLE IF NOT EXISTS payment_holds' in SRC)
check('payments ledger', 'CREATE TABLE IF NOT EXISTS payments' in SRC)
check('financial webhook transaction', 'const processEvent=db.transaction' in SRC)
# 166-185 state machines / business invariants
check('quote sent->payment start', "status='payment_starting'" in SRC)
check('quote payment start->required', "status='payment_required'" in SRC)
check('quote paid->job', "UPDATE quotes SET status='paid'" in SRC and "INSERT OR IGNORE INTO jobs" in SRC)
check('job allowed transitions', "scheduled:new Set(['in_progress','canceled'])" in SRC)
check('completion creates confirmation', 'INSERT OR IGNORE INTO completion_confirmations' in SRC)
check('completion creates payout ledger', 'INSERT INTO provider_payout_ledger' in SRC)
check('cancellation requires other party', 'against=req.account.account_id===job.customer_account_id' in SRC)
check('cancellation blocks closed jobs', "!['scheduled','in_progress'].includes(job.status)" in SRC)
check('open dispute duplicate prevention', 'You already have an open dispute' in SRC)
check('review only completed', "job.status!=='completed'" in SRC)
check('review unique lead', 'lead_id INTEGER NOT NULL UNIQUE' in schema)
check('change order customer approval', "status='pending_customer'" in SRC)
check('positive change payment state', "payment_status='checkout_pending'" in SRC)
check('negative change refund state', "payment_status='refunded'" in SRC)
check('refund failure explicit', "payment_status='refund_failed'" in SRC)
check('appointment exact conflict check', 'scheduled_at=?' in SRC)
check('appointment availability enforcement', 'providerSlotAvailable' in SRC)
check('appointment blackout enforcement', 'blackouts.some' in SRC)
check('appointment timezone conversion', 'Intl.DateTimeFormat' in SRC)
check('availability slot overlap prevention', 'start<previousEnd' in SRC)
# 186-205 external/API safety
check('source HTTPS validation', "u.protocol==='https:'" in SRC)
check('source host allowlist', 'sourceHostAllowlist.has(u.hostname)' in SRC)
check('source redirect disabled', "redirect:'error'" in SRC)
check('source timeout', 'AbortController' in SRC and '8000' in SRC)
check('source upstream size cap', '2_000_000' in SRC)
check('source item cap', 'items.slice(0,100)' in SRC)
check('source secret encrypted', 'encryptSecret' in SRC and 'decryptSecret' in SRC)
check('source credentials not public', 'config_enc' not in SRC[SRC.find("app.get('/api/admin/sources"):SRC.find("app.get('/api/admin/sources")+800])
check('webhook outbound signature', 'x-swiftquote-signature' in SRC)
check('webhook outbound timestamp', 'x-swiftquote-timestamp' in SRC)
check('OpenAI store false', 'store: false' in (ROOT/'ai-provider.js').read_text())
check('OpenAI bounded output', 'max_output_tokens' in (ROOT/'ai-provider.js').read_text())
check('AI input bounded', 'clean(req.body?.text,4000)' in SRC)
check('AI result normalized', 'JSON.parse(out)' in SRC and 'Array.isArray(parsed.questions)' in SRC)
check('AI no invented facts instruction', 'Never invent price' in SRC)
check('AI lead no contact detail instruction', 'Never repeat personal contact details' in SRC)
check('API strict JSON', "Content-Type must be application/json" in SRC)
check('global API timeout exists', 'server.requestTimeout' in SRC)
check('unhandled errors sanitized', "Internal server error." in SRC)
check('oversized request sanitized', "Request too large." in SRC)
check('invalid JSON sanitized', "Invalid JSON." in SRC)
# 206-225 frontend / ops
check('frontend escaping', 'function esc' in APP or 'const esc' in APP)
check('admin escaping', 'function esc' in ADM or 'const esc' in ADM)
check('no inline event handlers', not re.search(r'\bon(click|load|error|submit)\s*=',APP,re.I))
check('frontend no eval', not re.search(r'\beval\s*\(|\bnew\s+Function\s*\(',APP))
check('admin frontend no eval', not re.search(r'\beval\s*\(|\bnew\s+Function\s*\(',ADM))
check('customer dashboard exists', 'customer' in APP.lower())
check('provider payout UI exists', 'payout' in APP.lower())
check('provider availability UI exists', 'availability' in APP.lower())
check('customer service passport route', '/api/customer/service-passport/' in SRC)
check('job timeline route', '/api/jobs/:id/timeline' in SRC)
check('message read route', '/api/jobs/:id/messages/read' in SRC)
check('cancellation response route', '/api/cancellation-requests/:id/respond' in SRC)
check('public provider profile route', '/api/marketplace/providers/:id' in SRC)
check('Docker non-root', 'USER node' in (ROOT/'Dockerfile').read_text())
check('Docker healthcheck', 'HEALTHCHECK' in (ROOT/'Dockerfile').read_text())
check('Docker production env', 'ENV NODE_ENV=production' in (ROOT/'Dockerfile').read_text())
check('README caveat', 'live' in (ROOT/'README.md').read_text().lower() and 'production' in (ROOT/'README.md').read_text().lower())
check('audit and adversarial scripts included', (ROOT/'deep_audit.py').exists() and (ROOT/'adversarial_sim.py').exists())
# 226-245 advanced static invariants
check('GET public providers has no metric write', 'refreshProviderMetrics(p.id)' not in SRC[SRC.find("app.get('/api/marketplace/providers'"):SRC.find("app.get('/api/marketplace/providers'")+2600])
check('GET public profile has no metric write', 'refreshProviderMetrics(id)' not in SRC[SRC.find("app.get('/api/marketplace/providers/:id'"):SRC.find("app.get('/api/marketplace/providers/:id'")+1800])
check('GET price check has no benchmark write', 'updatePriceBenchmark(service)' not in SRC[SRC.find("app.get('/api/customer/price-check'"):SRC.find("app.get('/api/customer/price-check'")+700])
check('public provider profile uses configured service areas', 'configuredAreas' in SRC and 'provider_service_areas' in SRC[SRC.find("app.get('/api/marketplace/providers/:id'"):SRC.find("app.get('/api/marketplace/providers/:id'")+2200])
check('availability rejects invalid timezone', 'Invalid IANA timezone' in SRC)
check('availability rejects duplicate blackout', 'Duplicate blackout date' in SRC)
check('availability rejects reversed slots', 'end<=start' in SRC)
check('availability rejects overlapping slots', 'start<previousEnd' in SRC)
check('availability ZIP strictness', "^\\d{5}(?:-\\d{4})?$" in SRC)
check('stale quote payment cleanup', 'payment_starting' in SRC and '10*60_000' in SRC)
check('stale payment hold cleanup', "status='starting'" in SRC and '60*60*1000' in SRC)
check('stale change checkout cleanup', "checkout_starting" in SRC and 'created_at < ?' in SRC)
check('quote Stripe deterministic idempotency', 'swiftquote-quote-checkout-' in SRC)
check('change Stripe deterministic idempotency', 'swiftquote-change-checkout-' in SRC)
check('subscription deterministic idempotency', 'swiftquote-subscription-' in SRC)
check('connect deterministic idempotency', 'swiftquote-connect-account-' in SRC)
check('refund deterministic idempotency', 'swiftquote-change-refund-' in SRC)
check('payout deterministic idempotency', 'swiftquote-payout-' in SRC)
check('GET trust pure provider', 'providerReliability(req.account.account_id)' in SRC)
check('GET customer trust pure', 'customerReliability(req.account.account_id)' in SRC)
check('review risk uses lead id', 'function reviewRisk(rating,comment,accountId,leadId)' in SRC)
check('dispute duplicate prevention', 'You already have an open dispute' in SRC)
check('financial history protected retention', 'NOT EXISTS (SELECT 1 FROM jobs' in SRC and 'NOT EXISTS (SELECT 1 FROM quotes' in SRC)
# 246-260 package/archive integrity if zip is present
zip_candidates=list(Path('/mnt/data').glob('SwiftQuote-Production-DEEP-HARDENED-v*.zip'))
def archive_version(p):
    m=re.search(r'-v(\d+)\.zip$',p.name)
    return int(m.group(1)) if m else -1
if zip_candidates:
    z=max(zip_candidates,key=archive_version)
    try:
        with zipfile.ZipFile(z) as zz:
            bad=zz.testzip(); names=zz.namelist()
            archive_packages=[json.loads(zz.read(n)) for n in names if n.endswith('package.json')]
        check('latest archive readable',bad is None,str(z))
        check('archive excludes env',not any(n.endswith('.env') for n in names))
        check('archive excludes db',not any(n.endswith(('.db','.sqlite','.sqlite3')) for n in names))
        check('archive excludes node_modules',not any('/node_modules/' in n for n in names))
        check('archive contains server', 'server.js' in names)
        check('archive contains package', 'package.json' in names)
        check('archive contains Dockerfile', 'Dockerfile' in names)
        check('archive contains AI provider module', 'ai-provider.js' in names)
        check('archive contains AI provider tests', 'test/ai-provider.test.js' in names)
        check('archive excludes duplicate nested project', not any(n.startswith('swiftquote_work/') for n in names))
        check('archive package version matches source', any(p.get('version')==PKG.get('version') for p in archive_packages))
        check('archive has no private keys',not any(n.endswith(('.pem','.key','.p12')) for n in names))
    except Exception as e: check('latest archive readable',False,str(e))
else:
    check('latest archive readable',False,'no archive adjacent')

fails=[r for r in results if not r[1]]
print(f'EXTREME AUDIT: {len(results)-len(fails)}/{len(results)} PASS')
for i,(name,ok,detail) in enumerate(results,1):
    print(('PASS' if ok else 'FAIL'),f'{i:03d}',name,detail)
if fails: sys.exit(1)
